### ISSUE TITLE
Environment Domain Name lower case

### ISSUE THREAD

**Issue by kevinkems** [Fewiel/EnvironmentServer#103]
When creating a new environment, the value of the text field is displayed in small letters when entering the domain, even though you capitalize it.
This is confusing in the error message when creating displays "-YourUsername.shopdev.de Environment domain not allowed No spaces, a-z, 0-9 Example: my1test".

I would recommend that before submitting the form, the field content is automatically converted to lowercase.

**Comment by Fewiel** [comment]
The domain name is now completely checked, special characters replaced, lowercase, äöü converted and spaces taken out.

Thanks for the advice :)
