### ISSUE TITLE
Sortierung

### ISSUE THREAD

**Issue by Sceebo** [Fewiel/EnvironmentServer#42]
Sortierung der Umgebungen ggf. selbst festlegen oder nach Alphabet?
![image](https://user-images.githubusercontent.com/94826486/142869672-17e0ecf9-adf0-4d03-b25e-58d18bf3f2fc.png)

**Comment by Fewiel** [comment]
Will be added in the next update

**Comment by Fewiel** [comment]
And it's done ;) 

Sorting is now possible.
