### ISSUE TITLE
Snapshot vor der Installation erstellt und nach der Installation zurückgesetzt

### ISSUE THREAD

**Issue by Sceebo** [Fewiel/EnvironmentServer#44]
Wenn man ein Snapshot vor der Installation durchführt (also die Umgebung gerade erstellt hat) und diesen nach der Installation wiederherstellt, ist die Umgebung nachträglich nicht mehr erreichbar. 
![image](https://user-images.githubusercontent.com/94826486/142871125-d5f8a95c-aa0a-4050-8d43-d462294b5fbb.png)
![image](https://user-images.githubusercontent.com/94826486/142871186-80d642aa-02b1-454d-9799-a9eeba92fb6f.png)

Files scheinen korrekt wiederhergestellt worden zu sein:
![image](https://user-images.githubusercontent.com/94826486/142871317-65c9ac1d-55f7-4be3-a8bc-a6a8713470e2.png)
Log sagt dann:
[Mon Nov 22 13:35:43.961677 2021] [proxy_fcgi:error] [pid 282264] [client 172.16.10.220:63100] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught RuntimeException: Could not connect to database. Message from SQL Server: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/sklostermann/files/sw576/engine/Shopware/Components/DependencyInjection/Bridge/Db.php:97\nStack trace:\n#0 /home/sklostermann/files/sw576/engine/Shopware/Kernel.php(245): Shopware\\Components\\DependencyInjection\\Bridge\\Db::createPDO()\n#1 /home/sklostermann/files/sw576/engine/Shopware/Components/HttpCache/AppCache.php(256): Shopware\\Kernel->boot()\n#2 /home/sklostermann/files/sw576/vendor/symfony/http-kernel/HttpCache/HttpCache.php(452): Shopware\\Components\\HttpCache\\AppCache->forward()\n#3 /home/sklostermann/files/sw576/vendor/symfony/http-kernel/HttpCache/HttpCache.php(346): Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache->fetch()\n#4 /home/sklostermann/files/sw576/engine/Shopware/Components/HttpCache/AppCache.php(189): Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache->lookup()\n#5 /home/...', referer: http://sw576.sklostermann.env.shopware.in/backend/

**Comment by Fewiel** [comment]
Here the installer lock file will not have been restored correctly. Should work in the meantime, but is nonsensical. 

Why save an uninstalled version...?
