### ISSUE TITLE
automatic install via script

### ISSUE THREAD

**Issue by pattifix** [Fewiel/EnvironmentServer#46]
finish the entire SW install via script. 

SW5 example : 
```php recovery/install/index.php --no-interaction --quiet --no-skip-import --db-host="HOST" --db-user="DATENBANKUSER" --db-password="DATENBANK-PASSWORT" --db-name="DB-NAME" --shop-locale="de_DE" --shop-host="HOST" --shop-path="/PFAD" --shop-name="SHOPNAME" --shop-email="EMAIL" --shop-currency="EUR" --admin-username="ADMIN-USERNAME" --admin-password="ADMIN-PASSWORT" --admin-email="ADMIN-EMAIL" --admin-name="ADMIN-NAME" --admin-locale="de_DE"```

**Comment by Sceebo** [comment]
+1

**Comment by Sceebo** [comment]
SW6:
`php7.4 public/recovery/install/index.php --db-host="localhost" --db-port="3306" --db-user="sklostermann_sw6470test2"  --db-password="rVFRaSCzAHtQQTmz" --db-name="sklostermann_sw6470test2" --shop-locale="de-DE" --no-skip-import --shop-host="sw6470test2-sklostermann.shopdev.de" --shop-email="s.klostermann@shopware.com" --admin-username="demo" --admin-password="demo"  --admin-email="s.klostermann@shopware.com" --admin-firstname="demo" --admin-lastname="demo" --shop-currency="EUR" --shop-name="SW6.4.7.0-Test" --admin-locale="de-DE" -n`

Dabei steht das "-n" am Ende, dafür, dass keine Abfrage mehr erfolgt. 
Im Anschluss erfolgt der First-Wizard bei der ersten Anmeldung
![image](https://user-images.githubusercontent.com/94826486/147096024-82cf3949-4399-48c5-898d-cee1ab847cde.png)

Mögliche Variablen in SW6 sind:
`install [--db-host DB-HOST] [--db-port DB-PORT] [--db-user DB-USER] [--db-password DB-PASSWORD] [--db-name DB-NAME] [--no-skip-import] [--db-ssl-ca [DB-SSL-CA]] [--db-ssl-cert [DB-SSL-CERT]] [--db-ssl-key [DB-SSL-KEY]] [--db-ssl-dont-verify-cert [DB-SSL-DONT-VERIFY-CERT]] [--shop-locale SHOP-LOCALE] [--shop-host SHOP-HOST] [--shop-path SHOP-PATH] [--shop-name SHOP-NAME] [--shop-email SHOP-EMAIL] [--shop-currency SHOP-CURRENCY] [--shop-country SHOP-COUNTRY] [--skip-admin-creation] [--admin-username ADMIN-USERNAME] [--admin-password ADMIN-PASSWORD] [--admin-email ADMIN-EMAIL] [--admin-locale ADMIN-LOCALE] [--admin-firstname ADMIN-FIRSTNAME] [--admin-lastname ADMIN-LASTNAME]`

**Comment by Fewiel** [comment]
**Working example with theme compilation:**

php7.4 public/recovery/install/index.php --db-host="localhost" --db-port="3306" --db-user="pweitkamp_sw6installer" --db-password="wWw8eDzh9Ut5wMEX" --db-name="pweitkamp_sw6installer" --shop-locale="de-DE" --no-skip-import --shop-host="sw6installer-pweitkamp.shopdev.de" --shop-email="s.klostermann@shopware.com" --admin-username="demo" --admin-password="demo" --admin-email="s.klostermann@shopware.com" --admin-firstname="demo" --admin-lastname="demo" --shop-currency="EUR" --shop-name="SW6.4.7.0-Test" --admin-locale="de-DE" -n


bash bin/build.sh
bash bin/build-js.sh
bin/console theme:change --all Storefront
bin/console theme:compile
bin/console cache:clear

**Comment by Sceebo** [comment]
--shop-country="DEU"
Sonst ist das Land falsch vom Verkaufskanal

**Comment by Sceebo** [comment]
SW5:
php7.4 recovery/install/index.php --no-interaction --quiet --no-skip-import --db-host="localhost" --db-user="sklostermann_sw5installer" --db-password="fbQs54FhRo6nhrOX" --db-name="sklostermann_sw5installer" --shop-locale="de_DE" --shop-host="sw5installer-sklostermann.shopdev.de" --shop-name="SW5.7.6" --shop-email="s.klostermann@shopware.com" --shop-currency="EUR" --admin-username="demo" --admin-password="demo" --admin-email="s.klostermann@shopware.com" --admin-name="demo" --admin-locale="de_DE"
