### ISSUE TITLE
SW Version nicht korrekt

### ISSUE THREAD

**Issue by Sceebo** [Fewiel/EnvironmentServer#48]
SW Version wird nur noch mit 6 oder 5 ausgegeben.

![image](https://user-images.githubusercontent.com/94826486/143046234-b44550b5-9bf5-4378-8daf-911a4d8767f2.png)

**Comment by Sceebo** [comment]
Weiterhin Fehlerhaft:
![image](https://user-images.githubusercontent.com/94826486/143195701-3b7146f8-8f50-453f-9fb4-065bf82655d1.png)

**Comment by pattifix** [comment]
can confirm

**Comment by Fewiel** [comment]
Is now pushed to the shopware server. 
Should work now on new Environments
