### ISSUE TITLE
Sortierung Shopware 5 Versionen

### ISSUE THREAD

**Issue by Sceebo** [Fewiel/EnvironmentServer#58]
Shopware 5.6.10 ist zwischen  5.6.1 und 5.6.2
![image](https://user-images.githubusercontent.com/94826486/144003400-71017a1d-eff6-4399-90bc-822a6810d239.png)
Dies müsst eigentlich nach 5.6.9 kommen.

**Comment by Fewiel** [comment]
Now also affects version 6.4.10.0.   
Now classified as a blocker - fix asap
