### ISSUE TITLE
Environment names - autocorrection

### ISSUE THREAD

**Issue by Fewiel** [Fewiel/EnvironmentServer#60]
Automatically replace upper case, spaces and special characters

**Comment by Fewiel** [comment]
implemented

**Comment by Sceebo** [comment]
Environment Name with a "-" error shows
![image](https://user-images.githubusercontent.com/94826486/146770047-2ecf527a-4a2e-41a8-950d-486ac0363025.png)
![image](https://user-images.githubusercontent.com/94826486/146770058-22b0d13c-a00d-4ab9-b4de-31e2203abe41.png)

**Comment by Sceebo** [comment]
Punkte werden ebenfalls nicht ersetzt.
