### ISSUE TITLE
Showroom Theme cannot be uploaded (1.2.0)

### ISSUE THREAD

**Issue by Sceebo** [Fewiel/EnvironmentServer#73]
Fehlermeldung:
![image](https://user-images.githubusercontent.com/94826486/146766565-387f6b65-9df6-4500-8d7c-de025eec8e75.png)

Version 1.1.6 funktioniert.

**Comment by Sceebo** [comment]
![image](https://user-images.githubusercontent.com/94826486/146772232-973a460e-604b-4d7a-ba3f-e55f297df70f.png)
![image](https://user-images.githubusercontent.com/94826486/146772470-645e9f00-b993-4b17-a5a9-ba35ce1a268f.png)

**Comment by Fewiel** [comment]
fixed - max_post_size now 32M
