### ISSUE TITLE
SW 5.7.7 not installable 

### ISSUE THREAD

**Issue by pattifix** [Fewiel/EnvironmentServer#78]
SW 5.7.7 not installable (rooting seems to be incorrect)
![sw577](https://user-images.githubusercontent.com/59580630/149750288-23564ab7-095a-4f03-a45d-475670a066ac.jpg)

workaround -> move to "recovery -> install"

**Comment by Fewiel** [comment]
https://issues.shopware.com/issues/SW-26484

Broken Installation Package
